import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";

// Runs before relay-compiler. Seeds persisted-queries.json so the compiler
// doesn't bail on a missing file (it refuses to start when persistConfig
// points to a path that doesn't exist).
//
// Resolves against process.cwd() — crucible is a workspace package; this
// script is invoked from the consumer app's directory.
const appRoot = process.cwd();
const persisted = resolve(appRoot, "persisted-queries.json");
const resolverHeader = `// THIS FILE IS GENERATED BY CRUCIBLE — DO NOT EDIT.
// Relay scans src/ before Crucible codegen runs, so preflight emits the
// framework-owned client resolver source here.
`;
const hasRelayConfig = [
  "relay.config.json",
  "relay.config.js",
  "relay.config.cjs",
  "relay.config.mjs",
].some((file) => existsSync(resolve(appRoot, file)));

if (!existsSync(persisted)) {
  writeFileSync(persisted, "{}\n", "utf8");
  console.log("[crucible] seeded persisted-queries.json");
}

if (hasRelayConfig && existsSync(resolve(appRoot, "src"))) {
  const resolverFile = resolve(appRoot, "src", "__crucible__", "app-resolvers.ts");
  mkdirSync(dirname(resolverFile), { recursive: true });
  writeFileSync(resolverFile, `${resolverHeader}
import {
  storageLiveState,
  syncLiveState,
  type AppStorageSnapshot,
  type AppSyncSnapshot,
  type LiveState,
} from "react-crucible/runtime/app-graph.ts";

/**
 * @relayType CrucibleApp
 * @weak
 */
export type CrucibleApp = Record<string, never>;

/**
 * @relayType CrucibleStorage
 * @weak
 */
export type CrucibleStorage = Record<string, never>;

/**
 * @relayType CrucibleSync
 * @weak
 */
export type CrucibleSync = Record<string, never>;

/**
 * @relayField Query.app: CrucibleApp
 */
export function app(): CrucibleApp {
  return {};
}

/**
 * @relayField CrucibleApp.storage: CrucibleStorage
 */
export function storage(_app: CrucibleApp): CrucibleStorage {
  return {};
}

/**
 * @relayField CrucibleApp.sync: CrucibleSync
 */
export function sync(_app: CrucibleApp): CrucibleSync {
  return {};
}

/**
 * @relayField CrucibleStorage.persisted: Boolean
 * @live
 */
export function persisted(_storage: CrucibleStorage): LiveState<AppStorageSnapshot["persisted"]> {
  return storageLiveState("persisted");
}

/**
 * @relayField CrucibleStorage.usage: Float
 * @live
 */
export function usage(_storage: CrucibleStorage): LiveState<AppStorageSnapshot["usage"]> {
  return storageLiveState("usage");
}

/**
 * @relayField CrucibleStorage.quota: Float
 * @live
 */
export function quota(_storage: CrucibleStorage): LiveState<AppStorageSnapshot["quota"]> {
  return storageLiveState("quota");
}

/**
 * @relayField CrucibleStorage.usageRatio: Float
 * @live
 */
export function usageRatio(_storage: CrucibleStorage): LiveState<AppStorageSnapshot["usageRatio"]> {
  return storageLiveState("usageRatio");
}

/**
 * @relayField CrucibleSync.online: Boolean
 * @live
 */
export function online(_sync: CrucibleSync): LiveState<AppSyncSnapshot["online"]> {
  return syncLiveState("online");
}

/**
 * @relayField CrucibleSync.status: String
 * @live
 */
export function status(_sync: CrucibleSync): LiveState<AppSyncSnapshot["status"]> {
  return syncLiveState("status");
}

/**
 * @relayField CrucibleSync.pendingMutations: Int
 * @live
 */
export function pendingMutations(_sync: CrucibleSync): LiveState<AppSyncSnapshot["pendingMutations"]> {
  return syncLiveState("pendingMutations");
}

/**
 * @relayField CrucibleSync.lastSyncedAt: String
 * @live
 */
export function lastSyncedAt(_sync: CrucibleSync): LiveState<AppSyncSnapshot["lastSyncedAt"]> {
  return syncLiveState("lastSyncedAt");
}

/**
 * @relayField CrucibleSync.lastErrorMessage: String
 * @live
 */
export function lastErrorMessage(_sync: CrucibleSync): LiveState<AppSyncSnapshot["lastErrorMessage"]> {
  return syncLiveState("lastErrorMessage");
}

/**
 * @relayField CrucibleSync.retryAt: String
 * @live
 */
export function retryAt(_sync: CrucibleSync): LiveState<AppSyncSnapshot["retryAt"]> {
  return syncLiveState("retryAt");
}

/**
 * @relayField CrucibleSync.conflictCount: Int
 * @live
 */
export function conflictCount(_sync: CrucibleSync): LiveState<AppSyncSnapshot["conflictCount"]> {
  return syncLiveState("conflictCount");
}
`, "utf8");
}
