import { existsSync, mkdirSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import type {
    DiscoveredRoute,
    FrameLevel,
    RouteSegment,
    ServerRoute,
} from "./scan.ts";
import { relPosix } from "./scan.ts";
import { parsePage, type ParsedPage } from "./parse.ts";
import { writeIfChanged } from "./write-if-changed.ts";

export type EmitContext = {
    appRoot: string;
    outDir: string;
    // npm specifier for the crucible package itself, used in generated
    // `import …` statements. Defaults to "react-crucible". Override when
    // the package is published or aliased under a different name.
    crucibleSpecifier: string;
};

// Filename of the optional user config module. When present, codegen
// imports it from the emitted main.tsx and passes its `network` export
// to `createEnvironment`. The file is the first user-export-drives-
// codegen surface in Crucible — keep its shape stable; future
// env-level options live alongside `network` in the same module.
const CONFIG_FILENAME = "crucible.config.ts";

export const DEFAULT_CRUCIBLE_SPECIFIER = "react-crucible";

export type RouteWithPage = {
    route: DiscoveredRoute;
    parsed: ParsedPage;
};

const HEADER = `// THIS FILE IS GENERATED BY CRUCIBLE — DO NOT EDIT.
// Re-run \`bun run codegen\` after changing routes or page Queries types.
`;

export function emitAll(
    ctx: EmitContext,
    routes: ReadonlyArray<RouteWithPage>,
): void {
    mkdirSync(ctx.outDir, { recursive: true });
    mkdirSync(join(ctx.outDir, "entrypoints"), { recursive: true });

    for (const r of routes) emitEntrypoint(ctx, r);
    emitRoutesManifest(ctx, routes);
}

// Emit the React entry that boots the app. Users own only `src/app/`;
// createRoot / StrictMode / AppShell / environment wiring all live here.
//
// App-wide values (theme color, default title, etc.) are NOT configured
// here — they belong in `src/app/layout.tsx`'s `metadata` export, which
// merges over AppShell's hardcoded defaults at render time.
//
// Configuration that has to reach framework primitives at boot lives in
// an optional `src/app/crucible.config.ts`:
//   - `network` (#46) — threaded into `createEnvironment` so consumers
//     can supply a custom fetch (Idempotency-Key wrapper, telemetry,
//     etc.) without monkey-patching `globalThis.fetch`.
//   - `localGraphQL` — converted into a fetch via
//     `createLocalGraphQLFetch` so Relay can execute against a local
//     Pothos/Drizzle/SQLite schema without knowing a sync engine exists.
//   - `swUpdate` (#53) — threaded into `<AppShell>` so consumers can
//     tune the SW update lifecycle (idle threshold, observability
//     callbacks) per the `SwUpdateBehavior` shape from #29.
//
// Imports + props are conditional on which fields the user exports —
// apps that don't ship a config file get the original zero-config
// bundle; apps that ship a config but only export `network` get a
// bare `<AppShell>` (no swUpdate prop), and vice versa. This keeps
// the emitted main.tsx noise-free relative to actual config use.
/**
 * Emit `.crucible/server-routes.ts` — a Hono app that mounts every
 * `route.ts` file the user authored under `src/app/`, Next.js-style.
 * The user's `server.ts` imports this module and mounts it under `/`
 * (or wherever) on its top-level Hono app:
 *
 *   import serverRoutes from "./.crucible/server-routes.ts";
 *   app.route("/", serverRoutes);
 *
 * Empty when no `route.ts` files exist — emits an empty Hono app so
 * importing it never fails. Re-emitted on every codegen run; the
 * `writeIfChanged` guard keeps Vite's HMR quiet when the route set
 * hasn't changed.
 */
export function emitServerRoutes(
    ctx: EmitContext,
    routes: ReadonlyArray<ServerRoute>,
): void {
    const file = join(ctx.outDir, "server-routes.ts");
    const fileDir = dirname(file);

    const importLines = routes
        .map((r, i) => `import route${i} from "${relPosix(fileDir, r.file)}";`)
        .join("\n");

    const mountLines = routes
        .map((r, i) => `app.route(${JSON.stringify(r.urlPath)}, route${i});`)
        .join("\n");

    const content = `${HEADER}
import { Hono } from "hono";
${importLines}

const app = new Hono();
${mountLines}

export default app;
`;
    writeIfChanged(file, content);
}

export function emitMainEntry(ctx: EmitContext): void {
    const file = join(ctx.outDir, "main.tsx");
    const configPath = join(ctx.appRoot, "src", "app", CONFIG_FILENAME);
    const hasConfig = existsSync(configPath);
    const exports = hasConfig
        ? readConfigExports(configPath)
        : new Set<string>();
    const hasNetwork = exports.has("network");
    const hasLocalGraphQL = exports.has("localGraphQL");
    const hasSwUpdate = exports.has("swUpdate");

    // Build the import line incrementally so we only name what the user
    // actually exports. This prevents a "no exported member" type error
    // if someone writes a config file that, say, only sets `swUpdate`.
    const importNames: string[] = [];
    if (hasNetwork) importNames.push("network as __cruxNetwork");
    if (hasLocalGraphQL) importNames.push("localGraphQL as __cruxLocalGraphQL");
    if (hasSwUpdate) importNames.push("swUpdate as __cruxSwUpdate");
    const configImport =
        importNames.length > 0
            ? `import { ${importNames.join(", ")} } from "../src/app/crucible.config.ts";\n`
            : "";
    const localGraphQLImport = hasLocalGraphQL
        ? `import { createLocalGraphQLFetch, createLocalGraphQLSubscribe, prepareLocalGraphQL } from "${ctx.crucibleSpecifier}/runtime/local-graphql.ts";\n`
        : "";

    const prepareLocalGraphQL = hasLocalGraphQL
        ? `if (__cruxLocalGraphQL) await prepareLocalGraphQL(__cruxLocalGraphQL);
`
        : "";
    const envSetup = hasLocalGraphQL
        ? hasNetwork
            ? `const __cruxFetch = __cruxLocalGraphQL ? createLocalGraphQLFetch(__cruxLocalGraphQL) : __cruxNetwork?.fetch;
const __cruxSubscribe = __cruxLocalGraphQL ? createLocalGraphQLSubscribe(__cruxLocalGraphQL) : __cruxNetwork?.subscribe;
const environment = Crucible.createEnvironment({ fetch: __cruxFetch, subscribe: __cruxSubscribe, persistStore: __cruxLocalGraphQL ? false : true });`
            : `const environment = Crucible.createEnvironment({ fetch: __cruxLocalGraphQL ? createLocalGraphQLFetch(__cruxLocalGraphQL) : undefined, subscribe: __cruxLocalGraphQL ? createLocalGraphQLSubscribe(__cruxLocalGraphQL) : undefined, persistStore: __cruxLocalGraphQL ? false : true });`
        : hasNetwork
          ? `const environment = Crucible.createEnvironment({ fetch: __cruxNetwork?.fetch, subscribe: __cruxNetwork?.subscribe });`
          : `const environment = Crucible.createEnvironment();`;
    const appShellOpen = hasSwUpdate
        ? `<Crucible.AppShell swUpdate={__cruxSwUpdate}>`
        : `<Crucible.AppShell>`;

    const content = `${HEADER}
import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import * as Crucible from "${ctx.crucibleSpecifier}/crucible";
import { routes } from "./routes.ts";
${configImport}
${localGraphQLImport}
${prepareLocalGraphQL}${envSetup}

createRoot(document.getElementById("root")!).render(
  <StrictMode>
    ${appShellOpen}
      <Crucible.App routes={routes} environment={environment} />
    </Crucible.AppShell>
  </StrictMode>,
);
`;
    writeIfChanged(file, content);
}

// Read the user's `crucible.config.ts` source and return the set of
// top-level export names we recognize. We do a syntactic scan rather
// than a full TypeScript compile here for two reasons: (a) codegen
// runs every dev-server boot and on every file save, so it must be
// cheap; (b) we only care about three or four specific names —
// detecting them via regex is reliable for the patterns this file is
// expected to hold (`export const network = …`, `export const
// localGraphQL = …`, `export const swUpdate = …`, occasionally re-exports). If a user resorts to
// dynamic exports the codegen will simply not detect them and the
// emitted main.tsx will lack the corresponding wiring; that's a
// reasonable footgun cost for keeping codegen fast and synchronous.
function readConfigExports(configPath: string): Set<string> {
    const found = new Set<string>();
    let source: string;
    try {
        source = readFileSync(configPath, "utf8");
    } catch {
        return found;
    }
    source = stripCommentsAndStrings(source);
    // Recognize:
    //   export const X = …
    //   export let X = …
    //   export var X = …
    //   export { X }              ← bare re-export of a local binding
    //   export { foo as X }       ← aliased re-export
    // Only the known config-shape names are checked.
    const known = ["network", "localGraphQL", "swUpdate"] as const;
    for (const name of known) {
        if (hasDirectExportDeclaration(source, name) || hasNamedExport(source, name)) {
            found.add(name);
        }
    }
    return found;
}

function hasDirectExportDeclaration(source: string, name: string): boolean {
    const directDecl = /\bexport\s+(?:const|let|var)\s+/g;
    for (const match of source.matchAll(directDecl)) {
        const declaration = readDirectExportDeclaration(source, match.index + match[0].length);
        for (const declarator of splitTopLevelDeclarators(declaration)) {
            if (new RegExp(`^\\s*${name}\\b`).test(declarator)) return true;
        }
    }
    return false;
}

function readDirectExportDeclaration(source: string, start: number): string {
    let depth = 0;
    for (let i = start; i < source.length; i++) {
        const ch = source[i];
        if (ch === "{" || ch === "[" || ch === "(") depth++;
        if (ch === "}" || ch === "]" || ch === ")") depth = Math.max(0, depth - 1);
        if (depth === 0 && ch === ";") return source.slice(start, i);
        if (
            depth === 0 &&
            ch === "\n" &&
            !source.slice(start, i).trimEnd().endsWith(",") &&
            !/^\s*,/.test(source.slice(i + 1))
        ) {
            return source.slice(start, i);
        }
        if (depth === 0 && ch === "\n" && /^\s*export\b/.test(source.slice(i + 1))) {
            return source.slice(start, i);
        }
    }
    return source.slice(start);
}

function splitTopLevelDeclarators(declaration: string): string[] {
    const parts: string[] = [];
    let start = 0;
    let depth = 0;
    for (let i = 0; i < declaration.length; i++) {
        const ch = declaration[i];
        if (ch === "{" || ch === "[" || ch === "(") depth++;
        if (ch === "}" || ch === "]" || ch === ")") depth = Math.max(0, depth - 1);
        if (ch === "," && depth === 0) {
            parts.push(declaration.slice(start, i));
            start = i + 1;
        }
    }
    parts.push(declaration.slice(start));
    return parts;
}

function hasNamedExport(source: string, name: string): boolean {
    const exportBlock = /\bexport\s*\{([^}]*)\}/g;
    for (const match of source.matchAll(exportBlock)) {
        const specifiers = (match[1] ?? "").split(",");
        for (const specifier of specifiers) {
            const parts = specifier.trim().split(/\s+as\s+/);
            const exportedName = (parts[1] ?? parts[0])?.trim();
            if (exportedName === name) return true;
        }
    }
    return false;
}

function stripCommentsAndStrings(source: string): string {
    let out = "";
    for (let i = 0; i < source.length; i++) {
        const ch = source[i];
        const next = source[i + 1];

        if (ch === "/" && next === "/") {
            out += "  ";
            i += 2;
            while (i < source.length && source[i] !== "\n") {
                out += " ";
                i++;
            }
            if (i < source.length) out += source[i];
            continue;
        }

        if (ch === "/" && next === "*") {
            out += "  ";
            i += 2;
            while (i < source.length) {
                if (source[i] === "*" && source[i + 1] === "/") {
                    out += "  ";
                    i++;
                    break;
                }
                out += source[i] === "\n" ? "\n" : " ";
                i++;
            }
            continue;
        }

        if (ch === '"' || ch === "'" || ch === "`") {
            const quote = ch;
            out += " ";
            while (++i < source.length) {
                const current = source[i];
                out += current === "\n" ? "\n" : " ";
                if (current === "\\") {
                    if (i + 1 < source.length) {
                        i++;
                        out += source[i] === "\n" ? "\n" : " ";
                    }
                    continue;
                }
                if (current === quote) break;
            }
            continue;
        }

        if (ch === "/" && isRegexLiteralStart(out)) {
            out += " ";
            let inClass = false;
            while (++i < source.length) {
                const current = source[i];
                out += current === "\n" ? "\n" : " ";
                if (current === "\\") {
                    if (i + 1 < source.length) {
                        i++;
                        out += source[i] === "\n" ? "\n" : " ";
                    }
                    continue;
                }
                if (current === "[") inClass = true;
                if (current === "]") inClass = false;
                if (current === "/" && !inClass) {
                    while (/[a-z]/i.test(source[i + 1] ?? "")) {
                        i++;
                        out += " ";
                    }
                    break;
                }
            }
            continue;
        }

        out += ch;
    }
    return out;
}

function isRegexLiteralStart(strippedPrefix: string): boolean {
    const trimmed = strippedPrefix.trimEnd();
    if (trimmed.length === 0) return true;
    if (/(^|[^\w$])(?:return|throw|case|delete|typeof|void|new|yield)$/.test(trimmed)) {
        return true;
    }
    const prev = trimmed[trimmed.length - 1];
    return prev != null && "([{=,:;!&|?+-*~^<>".includes(prev);
}

function emitEntrypoint(ctx: EmitContext, rwp: RouteWithPage): void {
    const file = join(ctx.outDir, "entrypoints", `${rwp.route.id}.ts`);
    const segments = rwp.route.segments;
    emitEntrypointModule({
        outFile: file,
        sourceFile: rwp.route.pageFile,
        parsed: rwp.parsed,
        segments,
        id: rwp.route.id,
        kind: "page",
        crucibleSpecifier: ctx.crucibleSpecifier,
    });
    // Sub-entrypoints declared via the page's `EntryPoints` type. Each becomes
    // its own emitted module. Recursion happens here too — a sub can declare
    // its own `EntryPoints` and we walk it.
    for (const ep of rwp.parsed.entryPoints) {
        emitSubEntrypointModule({
            ctx,
            parentRouteId: rwp.route.id,
            entryName: ep.fieldName,
            sourceFile: ep.modulePath + ".tsx",
            segments,
        });
    }
}

type EmitModuleOpts = {
    outFile: string;
    sourceFile: string;
    parsed: ParsedPage;
    segments: ReadonlyArray<RouteSegment>;
    id: string;
    kind: "page" | "sub";
    crucibleSpecifier: string;
};

function emitEntrypointModule(opts: EmitModuleOpts): void {
    const fileDir = dirname(opts.outFile);
    const sourcePathRel = relPosix(fileDir, opts.sourceFile);

    // Two imports per query, intentionally split across two artifacts:
    //   - VALUE: `<Op>$parameters.ts` — relay-compiler's preload header
    //     (operation id + name + kind, ~20 lines). Tiny.
    //   - TYPE: `<Op>.graphql.ts` — the full normalized AST + variable
    //     types. Heavy. We only need the type at the entry-point boundary
    //     (`variables: <Op>["variables"]`); types are erased at runtime.
    //
    // The page module itself still imports `.graphql.ts` for
    // `usePreloadedQuery(graphql\`...\`, queries.x)`, but the page is
    // code-split per route — its AST cost is amortized over actual route
    // visits. The entry-point is in the boot bundle (it's part of the
    // routing manifest), so its imports stay in the critical path. With
    // the parameters-only import, N pages contribute N × tiny-headers
    // instead of N × full-ASTs to boot.
    //
    // `$parameters.ts` is only emitted for queries marked `@preloadable`.
    // Pages must declare their queries as preloadable (Crucible's
    // convention enforces this anyway) — if a query isn't preloadable,
    // codegen fails at relay-compile, not here.
    const queryImports = opts.parsed.queries
        .map((q, i) => {
            const stem = q.artifactPath.replace(/\.graphql$/, "");
            const parametersRel =
                relPosix(fileDir, `${stem}$parameters`) + ".ts";
            const typeRel = relPosix(fileDir, q.artifactPath) + ".ts";
            return `import query${i} from "${parametersRel}";\nimport type { ${q.artifactExport} } from "${typeRel}";`;
        })
        .join("\n");

    const paramNames = new Set<string>();
    for (const seg of opts.segments) {
        if (seg.kind === "param" || seg.kind === "catchall")
            paramNames.add(seg.name);
    }

    let usesParams = false;
    const queryEntries = opts.parsed.queries
        .map((q, i) => {
            const vars =
                opts.parsed.operationVariables.get(q.artifactExport) ?? [];
            const mapped = vars.filter((v) => paramNames.has(v));
            if (mapped.length > 0) usesParams = true;
            const variablesLiteral =
                mapped.length === 0
                    ? "{}"
                    : `{ ${mapped.map((v) => `${v}: params.${v}`).join(", ")} }`;
            return `      ${q.fieldName}: { parameters: query${i}, variables: ${variablesLiteral} },`;
        })
        .join("\n");

    const preloadParam = usesParams ? "{ params }" : "_preload";

    const queriesType = opts.parsed.queries.length
        ? `{
${opts.parsed.queries
    .map(
        (q, i) =>
            `      ${q.fieldName}: { parameters: typeof query${i}; variables: ${q.artifactExport}["variables"] };`,
    )
    .join("\n")}
    }`
        : "Record<string, never>";

    // Page modules receive the unwrapped `data` (the single @preloadable
    // PreloadedQuery), `params`, `search`, and the resolved sub-entrypoints
    // map. Sub-entrypoints get only `data` + nested `entryPoints`.
    //
    // The page's `Route` runtime export carries the title + search-spec
    // config; PageRenderer reads it directly. We don't type `Route` on
    // the module shape because emit can't easily round-trip the typed
    // `RouteObject` generics — PageRenderer reads it via a structural
    // cast at runtime.
    const isPage = opts.kind === "page";
    const dataField = opts.parsed.queries.length
        ? `data: Queries["data"]["parameters"] extends infer P ? import("react-relay").PreloadedQuery<${
              opts.parsed.queries[0]!.artifactExport
          }> : never`
        : `data: undefined`;
    const moduleType = isPage
        ? `Promise<{
        default: ComponentType<{ ${dataField}; params: any; search: any; entryPoints: Record<string, any> }>;
      }>`
        : `Promise<{
        default: ComponentType<{ ${dataField}; entryPoints: Record<string, any> }>;
      }>`;

    const standardSchemaImport = "";

    // Sub-entrypoints declared by THIS module. Imports + entryPoints field on
    // the emitted entrypoint object. Recursion: any sub-entrypoint can itself
    // declare more sub-entrypoints.
    const subEpImports: string[] = [];
    const subEpFields: string[] = [];
    for (const ep of opts.parsed.entryPoints) {
        const subId = `${opts.id}.${ep.fieldName}`;
        const subFile = `./${subId}.ts`;
        const ident = `__ep_${ep.fieldName.replace(/[^a-zA-Z0-9]/g, "_")}`;
        subEpImports.push(`import ${ident} from "${subFile}";`);
        subEpFields.push(`    ${ep.fieldName}: ${ident},`);
    }
    const entryPointsField =
        subEpFields.length > 0
            ? `\n  entryPoints: {\n${subEpFields.join("\n")}\n  },`
            : "";

    const epType = isPage ? "EntryPoint" : "SubEntryPoint";

    const content = `${HEADER}
import { JSResource, type ${epType} } from "${opts.crucibleSpecifier}/runtime/entrypoint.ts";
import type { ComponentType } from "react";
import type { Metadata } from "${opts.crucibleSpecifier}/runtime/metadata.tsx";
${standardSchemaImport}${queryImports}
${subEpImports.join("\n")}

type Queries = ${queriesType};

const entrypoint: ${epType}<Queries> = {
  root: JSResource(
    "${opts.id}",
    () =>
      import("${sourcePathRel}") as ${moduleType},
  ),
  getPreloadProps: (${preloadParam}) => ({
    queries: {
${queryEntries}
    } as Queries,
  }),${entryPointsField}
};

export default entrypoint;
`;
    writeIfChanged(opts.outFile, content);
}

function emitSubEntrypointModule(opts: {
    ctx: EmitContext;
    parentRouteId: string;
    entryName: string;
    sourceFile: string;
    segments: ReadonlyArray<RouteSegment>;
}): void {
    const subId = `${opts.parentRouteId}.${opts.entryName}`;
    const outFile = join(opts.ctx.outDir, "entrypoints", `${subId}.ts`);
    const subParsed = parsePage(opts.sourceFile);
    emitEntrypointModule({
        outFile,
        sourceFile: opts.sourceFile,
        parsed: subParsed,
        segments: opts.segments,
        id: subId,
        kind: "sub",
        crucibleSpecifier: opts.ctx.crucibleSpecifier,
    });
    // Recurse into nested entry points declared by this sub.
    for (const nested of subParsed.entryPoints) {
        emitSubEntrypointModule({
            ctx: opts.ctx,
            parentRouteId: subId,
            entryName: nested.fieldName,
            sourceFile: nested.modulePath + ".tsx",
            segments: opts.segments,
        });
    }
}

type ResourceRegistry = {
    imports: string[];
    // file → resource ident (e.g. layout0)
    byFile: Map<string, string>;
    counters: Record<string, number>;
};

function makeRegistry(): ResourceRegistry {
    return { imports: [], byFile: new Map(), counters: {} };
}

function frameResources(
    reg: ResourceRegistry,
    frame: FrameLevel,
    fileDir: string,
): { layout?: string; loading?: string; error?: string; notFound?: string } {
    const out: ReturnType<typeof frameResources> = {};

    // Layouts code-split alongside the page chunk (both wait for the same
    // navigation), so they're lazy via JSResource. Boundary fallbacks must
    // render synchronously when their boundary fires — a Suspense fallback
    // can't itself suspend — so they're imported eagerly.
    if (frame.layout) {
        let ident = reg.byFile.get(frame.layout);
        if (!ident) {
            const counter = reg.counters["layout"] ?? 0;
            reg.counters["layout"] = counter + 1;
            ident = `layout${counter}`;
            reg.byFile.set(frame.layout, ident);
            const rel = relPosix(fileDir, frame.layout);
            reg.imports.push(
                `const ${ident} = JSResource("${ident}", () => import("${rel}") as Promise<{ default: ComponentType<{ children: ReactNode } & Record<string, ReactNode>>; metadata?: Metadata }>);`,
            );
        }
        out.layout = ident;
    }

    const eagerSlots: ReadonlyArray<{
        key: "loading" | "error" | "notFound";
        kind: string;
    }> = [
        { key: "loading", kind: "loading" },
        { key: "error", kind: "error" },
        { key: "notFound", kind: "notFound" },
    ];
    for (const slot of eagerSlots) {
        const file = frame[slot.key];
        if (!file) continue;
        let ident = reg.byFile.get(file);
        if (!ident) {
            const counter = reg.counters[slot.kind] ?? 0;
            reg.counters[slot.kind] = counter + 1;
            ident = `${slot.kind}${counter}`;
            reg.byFile.set(file, ident);
            const rel = relPosix(fileDir, file);
            reg.imports.push(`import ${ident} from "${rel}";`);
        }
        out[slot.key] = ident;
    }
    return out;
}

function emitRoutesManifest(
    ctx: EmitContext,
    routes: ReadonlyArray<RouteWithPage>,
): void {
    const file = join(ctx.outDir, "routes.ts");
    const fileDir = dirname(file);

    const segmentsLiteral = (rwp: RouteWithPage) =>
        `[${rwp.route.segments
            .map((s) => {
                if (s.kind === "literal")
                    return `{ kind: "literal", value: ${JSON.stringify(s.value)} }`;
                if (s.kind === "param")
                    return `{ kind: "param", name: ${JSON.stringify(s.name)} }`;
                return `{ kind: "catchall", name: ${JSON.stringify(s.name)} }`;
            })
            .join(", ")}]`;

    const reg = makeRegistry();
    const routeBlocks = routes.map((rwp) => {
        const frameLines = rwp.route.frames.map((frame) => {
            const r = frameResources(reg, frame, fileDir);
            const props: string[] = [];
            if (r.layout) props.push(`layout: ${r.layout}`);
            if (r.loading) props.push(`loading: ${r.loading}`);
            if (r.error) props.push(`error: ${r.error}`);
            if (r.notFound) props.push(`notFound: ${r.notFound}`);
            if (frame.slots && frame.slots.length > 0)
                props.push(`slots: ${JSON.stringify(frame.slots)}`);
            props.push(`urlDepth: ${frame.urlDepth}`);
            return `      { ${props.join(", ")} }`;
        });
        const slotProp = rwp.route.slot
            ? `\n    slot: ${JSON.stringify(rwp.route.slot)},`
            : "";
        const interceptProp = rwp.route.intercept
            ? `\n    intercept: ${JSON.stringify(rwp.route.intercept)},`
            : "";
        const kindProp =
            rwp.route.kind === "default" ? `\n    kind: "default",` : "";
        return `  {
    path: ${JSON.stringify(rwp.route.urlPath)},
    segments: ${segmentsLiteral(rwp)},
    frames: [
${frameLines.join(",\n")}
    ],
    entrypoint: ${jsId(rwp.route.id)},${slotProp}${interceptProp}${kindProp}
  },`;
    });

    const entrypointImports = routes
        .map(
            (rwp) =>
                `import ${jsId(rwp.route.id)} from "./entrypoints/${rwp.route.id}.ts";`,
        )
        .join("\n");

    const content = `${HEADER}
import type { ComponentType, ReactNode } from "react";
import { JSResource } from "${ctx.crucibleSpecifier}/runtime/entrypoint.ts";
import type { RouteRecord } from "${ctx.crucibleSpecifier}/runtime/router/types.ts";
import type { Metadata } from "${ctx.crucibleSpecifier}/runtime/metadata.tsx";
${entrypointImports}

${reg.imports.join("\n")}

export const routes: ReadonlyArray<RouteRecord> = [
${routeBlocks.join("\n")}
];
`;
    writeIfChanged(file, content);
}

function jsId(routeId: string): string {
    return "ep_" + routeId.replace(/[^a-zA-Z0-9]/g, "_");
}
